Fix chooser crash on SDK < 29 (Android < 10)
Thank you Google Play Pre Launch Report:

android.view.InflateException: Binary XML file line #21: Binary XML file line #21: Error inflating class <unknown>
...
Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #3: <item> tag requires a 'drawable' attribute or child tag defining a drawable

I guess versions this old don't like color selectors which I started using in
commit 83d38596bbd44a991a57dc41bd69314f001eaf8c and it'd be fiddly to unpick,
so just disable the current-game highlight on those versions for now.